InventoryProject/Models/History.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryProject.Models
{
    public class History
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public Equipment Equipment { get; set; }
        public string EquipmentStatus { get; set; }
        public HistoryType Type { get; set; }
        public int? EntityID { get; set; }
        public string Commentary { get; set; }
        public int? OperatingHours { get; set; }
    }
}

InventoryProject/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using InventoryProject.Controllers.Interfaces;
using InventoryProject.Helpers;
using InventoryProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace InventoryProject.Controllers
{
    public class ClientsController : Controller
    {
        private readonly InventoryContext db;
        public ClientsController(InventoryContext context)
        {
            db = context;
        }

        // SORTING
        private List<Client> Sorting(string sortOrder, List<Client> clients)
        {
            switch (sortOrder)
            {
                case "id_desc":
                    clients = clients.OrderByDescending(s => s.Id).ToList();
                    break;
                case "id":
                    clients = clients.OrderBy(s => s.Id).ToList();
                    break;
                case "name_desc":
                    clients = clients.OrderByDescending(s => s.Name).ToList();
                    break;
                default:
                    clients = clients.OrderBy(s => s.Name).ToList();
                    break;
            }
            return clients;
        }

        // LIST
        public ActionResult Index(string oldSortOrder, string newSortOrder, string searchString, int? page, string currentFilter)
        {
            var clients = db.Clients.ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                clients = clients.Where(s => s.Name.ToLower().Contains(searchString.ToLower())).ToList(); 
            }

            if (string.IsNullOrEmpty(newSortOrder))
            {
                newSortOrder = "name";
            }
            else if (newSortOrder == oldSortOrder)
            {
                newSortOrder += "_desc";
            }
            ViewBag.CurrentSort = newSortOrder;
            clients = Sorting(newSortOrder, clients);

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            ViewBag.ClientContracts = db.Agreements.Include(x => x.Client).ToList();
            ViewBag.ClientWells = db.Wells.Include(x => x.Client).ToList();
            return View(clients.ToPagedList(pageNumber, pageSize));
        }

        // DETAILS 
        [HttpGet("/[controller]/[action]/{id}")]
        public ActionResult Details(int id)
        {
            var client = db.Clients.FirstOrDefault(x => x.Id == id);
            ViewBag.ClientContracts = db.Agreements.Where(x => x.Client.Id == client.Id).ToList();
            ViewBag.ClientWells = db.Wells.Where(x => x.Client.Id == client.Id).ToList();
            return View(client);
        }

        // CREATE CLIENT
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        // ADD CONTRACT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddContract(int clientId, string contractNum)
        {
            try
            {
                var client = db.Clients.FirstOrDefault(x => x.Id == clientId);
                db.Agreements.Add(new Contract() { ContractNumber = contractNum, Client = client });
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { id = clientId });
            }
            catch
            {
                return RedirectToAction("Details", new { id = clientId });
            }
        }

        // ADD WELL
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddWell(int clientId, string title)
        {
            try
            {
                var client = db.Clients.FirstOrDefault(x => x.Id == clientId);
                db.Wells.Add(new Well() { Title = title, Client = client });
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { id = clientId });
            }
            catch
            {
                return RedirectToAction("Details", new { id = clientId });
            }
        }

        // EDIT CONTRACT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditContract(int clientId, int contractId, string editContractNum)
        {
            try
            {
                var contract = db.Agreements.FirstOrDefault(x => x.Id == contractId);
                contract.ContractNumber = editContractNum;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { id = clientId });
            }
            catch
            {
                return RedirectToAction("Details", new { id = clientId });
            }
        }

        // EDIT WELL
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditWell(int clientId, int wellId, string editTitle)
        {
            try
            {
                var well = db.Wells.FirstOrDefault(x => x.Id == wellId);
                well.Title = editTitle;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { id = clientId });
            }
            catch
            {
                return RedirectToAction("Details", new { id = clientId });
            }
        }

        // EDIT CLIENT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditClient(int clientId, string editName)
        {
            try
            {
                var client = db.Clients.FirstOrDefault(x => x.Id == clientId);
                client.Name = editName;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { id = clientId });
            }
            catch
            {
                return RedirectToAction("Details", new { id = clientId });
            }
        }
    }




    // TODO : Removing Clients, Contracts, Wells
    // GET: ClientsController/Delete/5
    //public ActionResult Delete(int id)
    //{
    //    return View();
    //}

    //// POST: ClientsController/Delete/5
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public ActionResult Delete(int id, IFormCollection collection)
    //{
    //    try
    //    {
    //        return RedirectToAction(nameof(Index));
    //    }
    //    catch
    //    {
    //        return View();
    //    }
    //}
}

InventoryProject/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Spreadsheet;
using InventoryProject.Helpers;
using InventoryProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InventoryProject.Controllers
{
    public class SharedController : Controller
    {
        private readonly InventoryContext db;
        public SharedController(InventoryContext context)
        {
            db = context;
        }

        // Add note
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddNote(int equipmentId, string entityType, int? entityId, string noteText, string controllerId)
        {
            try
            {
                var equipment = db.Equipment.Include(x => x.Status)
                    .FirstOrDefault(x => x.Id == equipmentId);
                var type = db.HistoryTypes.FirstOrDefault(x => x.Type == entityType);
                History history = new History()
                {
                    Date = DateTime.Now,
                    EquipmentStatus = equipment.Status.Title,
                    Type = type,
                    EntityID = entityId,
                    Equipment = equipment,
                    Commentary = noteText
                };
                db.History.Add(history);
                await db.SaveChangesAsync();

                if (controllerId == "Equipment")
                {
                    return RedirectToAction("Details", "Equipment", new { id = equipmentId });
                }
                else
                {
                    return RedirectToAction("Details", controllerId, new { id = entityId });
                } 
                
            }
            catch
            {
                return RedirectToAction("Index", "Equipment");
            }
        }

        // Add Hours
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddHours(int equipmentId, int orderId, string controllerId, string hours, string minutes)
        {
            try
            {
                var equipment = db.Equipment.Include(x => x.Status)
                    .FirstOrDefault(x => x.Id == equipmentId);
                int operatingHours = int.Parse(hours) * 60 + int.Parse(minutes);
                equipment.OperatingTime -= operatingHours;
                if (equipment.OperatingTime < 0)
                {
                    equipment.OperatingTime = 0;
                }
                
                string time = (equipment.OperatingTime / 60) + ":";
                if (equipment.OperatingTime % 60 < 10)
                {
                    time += "0";
                }
                time += (equipment.OperatingTime % 60).ToString();

                var type = db.HistoryTypes.FirstOrDefault(x => x.Type == "Order");
                History history = new History()
                {
                    Date = DateTime.Now,
                    EquipmentStatus = equipment.Status.Title,
                    Type = type,
                    EntityID = orderId,
                    Equipment = equipment,
                    Commentary = "Operating hours: " + hours + ":"+ minutes + ", resuorse left - " + time
                };

                db.History.Add(history);
                await db.SaveChangesAsync();

                if (controllerId == "Equipment")
                {
                    return RedirectToAction("Details", "Equipment", new { id = equipmentId });
                }
                else
                {
                    return RedirectToAction("Details", controllerId, new { id = orderId });
                }
            }
            catch
            {
                return RedirectToAction("Index", "Equipment");
            }
        }

        // close order
        public IActionResult CloseOrder(int orderId, string controllerId)
        {
            try
            {
                var order = db.Orders.Include(x=>x.Equipment).FirstOrDefault(x => x.Id == orderId);
                var equipment = db.Equipment.FirstOrDefault(x => x.Id == order.Equipment.Id);
                var status = db.EquipmentStatuses.FirstOrDefault(x => x.Title == "WS");
                order.IsOpen = false;
                order.OrderFinish = DateTime.Now;
                equipment.Status = status;

                var type = db.HistoryTypes.FirstOrDefault(x => x.Type == "Order");
                History history = new History()
                {
                    Date = DateTime.Now,
                    EquipmentStatus = status.Title,
                    Type = type,
                    EntityID = order.Id,
                    Equipment = equipment,
                    Commentary = "Order closed"
                };
                db.History.Add(history);

                db.SaveChanges();
                if (controllerId == "Equipment")
                {
                    return RedirectToAction("Details", "Equipment", new { id = equipment.Id });
                }
                else
                {
                    return RedirectToAction("Details", "Orders", new { id = orderId });
                }
            }
            catch
            {
                return RedirectToAction("Index", "Orders");
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UploadImg(int equipmentId, int maintenanceId, string controllerId, IFormFileCollection imgfilepath)
        {
            try
            {
                int added = 0;
                string addedimages = "Scans added: ";
                var maintenance = db.Maintenances.FirstOrDefault(x => x.Id == maintenanceId);
                foreach (var uploadedFile in imgfilepath)
                {
                    string imagestring = ImageHelper.ImageToBase64(uploadedFile);
                    DocScan scan = new DocScan() { base64Image = imagestring, Maintenance = maintenance, Filename = uploadedFile.FileName };
                    db.DocScans.Add(scan);
                    added++;
                    addedimages += scan.Filename + ", ";
                }

                if (added > 0)
                {
                    addedimages = addedimages.Substring(0, addedimages.Length - 2);
                    var equipment = db.Equipment.Include(x => x.Status)
                        .FirstOrDefault(x => x.Id == equipmentId);
                    var type = db.HistoryTypes.FirstOrDefault(x => x.Type == "Maintenance");
                    History history = new History()
                    {
                        Date = DateTime.Now,
                        EquipmentStatus = equipment.Status.Title,
                        Type = type,
                        EntityID = maintenance.Id,
                        Equipment = equipment,
                        Commentary = addedimages
                    };
                    db.History.Add(history);
                }                

                await db.SaveChangesAsync();
                if (controllerId == "Equipment")
                {
                    return RedirectToAction("Details", "Equipment", new { id = equipmentId });
                }
                else
                {
                    return RedirectToAction("Details", "Maintenance", new { id = maintenanceId });
                }
            }
            catch
            {
                return RedirectToAction("Index", "Maintenance");
            }
        }

        public IActionResult MaintenanceChangeStatus(int equipmentId, int maintenanceId, string controllerId)
        {
            try
            {
                var equipment = db.Equipment.FirstOrDefault(x => x.Id == equipmentId);
                var status = db.EquipmentStatuses.FirstOrDefault(x => x.Title == "RP");
                equipment.Status = status;

                var type = db.HistoryTypes.FirstOrDefault(x => x.Type == "Maintenance");
                History history = new History()
                {
                    Date = DateTime.Now,
                    EquipmentStatus = status.Title,
                    Type = type,
                    EntityID = maintenanceId,
                    Equipment = equipment,
                    Commentary = "Status changed (Need Repairs)"
                };
                db.History.Add(history);

                db.SaveChanges();

                if (controllerId == "Equipment")
                {
                    return RedirectToAction("Details", "Equipment", new { id = equipmentId });
                }
                else
                {
                    return RedirectToAction("Details", "Maintenance", new { id = maintenanceId });
                }
            }
            catch
            {
                return RedirectToAction("Index", "Maintenance");
            }
        }

        // SET DUE DATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetMaintenanceDueDate(int equipmentId, int maintenanceId, string controllerId, string dueDate)
        {
            try
            {                
                var equipment = db.Equipment.Include(x => x.Status)
                    .FirstOrDefault(x => x.Id == equipmentId);
                var maintenance = db.Maintenances.FirstOrDefault(x => x.Id == maintenanceId);

                string[] date = dueDate.Split('-');
                DateTime setDate = new DateTime(int.Parse(date[0]), int.Parse(date[1]), int.Parse(date[2]));
                maintenance.MaintenanceExpectedFinish = setDate;

                var type = db.HistoryTypes.FirstOrDefault(x => x.Type == "Maintenance");
                History history = new History()
                {
                    Date = DateTime.Now,

InventoryProject/Views/Shared/_FormAddNote.cshtml
    <div class="form-pos form-info block-width-100">
        <div class="form-info__heading">@((string)ViewData["Heading"])</div>
        <form method="post"
              asp-controller="Shared" asp-action="AddNote"
              asp-route-equipmentId="@ViewData["EquipmentId"]"
              asp-route-entityType="@ViewData["EntityType"]"
              asp-route-entityId="@ViewData["EntityId"]"
              asp-route-controllerId="@ViewData["Controller"]">
            <div class="form-group">
                <textarea required class="form-control" name="noteText"></textarea>
            </div>
            <button class="btn btn-primary">Add Note</button>
        </form>
    </div>

InventoryProject/Views/Shared/_History.cshtml
@{
    List<History> history = new List<History>();
    var temp = ViewData["History"] as List<History>;
    if (temp != null)
    {
        history = temp;
        if (ViewData["EntityId"] != null)
        {
            history = history.Where(x => x.EntityID == (int)ViewData["EntityId"]
                && x.Type.Type == (string)ViewData["Type"]).ToList();
        }
    }
}
@{
    if (history.Any())
    {
        <div class="history">
            <div class="history-heading">
                History
            </div>
            <!--- LATER - dropown -->
            <div class="history-pos">
                <table class="table table-history">
                    <thead>
                        <tr>
                            <th>
                                Date
                            </th>
                            @if ((string)ViewData["Type"] == "General")
                            {
                                <th>
                                    STatus
                                </th>
                            }
                            <th>
                                Note
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in history)
                        {
                            <tr>
                                <td>
                                    @item.Date
                                </td>
                                @if ((string)ViewData["Type"] == "General")
                                {
                                    <td>
                                        @item.EquipmentStatus
                                    </td>
                                }
                                <td>
                                    @if (item.OperatingHours != null)
                                    {
                                        <p>
                                            Operating hours:
                                            <span class="hours">
                                                @(item.OperatingHours / 60):@{
                                                    string minutes;
                                                    if (item.OperatingHours % 60 < 10)
                                                    {
                                                        minutes = "0" + (item.OperatingHours % 60);
                                                    }
                                                    else
                                                    {
                                                        minutes = (item.OperatingHours % 60).ToString();
                                                    }
                                                    @minutes
                                                }
                                            </span>
                                            <span>hours</span>
                                        </p>
                                    }
                                    @if (item.Commentary.Length > 0)
                                    {
                                        <p>@item.Commentary</p>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="history-navigation">
                    <div class="simple-pagination-first"></div>
                    <div class="simple-pagination-previous"></div>
                    <div class="simple-pagination-page-numbers"></div>
                    <div class="simple-pagination-next"></div>
                    <div class="simple-pagination-last"></div>
                </div>
            </div>
        </div>
    }
}

InventoryProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryProject</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/jquery.fancybox.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>

    <div class="main">
        <!-- HEADER -->
        <header class="header">
            <div class="container">
                <h1 class="header-heading">InventoryProject</h1>
                <div class="header-nav">
                    <span class="header-nav__icon"><i></i></span>
                    <div class="header-nav__container">
                        <a asp-controller="Equipment" asp-action="Index" class="header-nav__item">Equipment</a>
                        <a asp-controller="Clients" asp-action="Index" class="header-nav__item">Clients</a>
                        <a asp-controller="Orders" asp-action="Index" class="header-nav__item">Orders</a>
                        <a asp-controller="Maintenance" asp-action="Index" class="header-nav__item">Maintenance</a>
                    </div>                    
                </div>
            </div>
        </header>

        <!-- CONTENT -->
        <div class="content">
            <div class="container">

                @RenderBody()

            </div>
        </div>

        <!-- FOOTER -->
        <footer class="footer">
            <p class="footer-copyright">
                &copy; 2020 - Infocom LTD, Kateryna Sahaidak
            </p>
        </footer>
    </div>

    <script src="~/js/jquery-simple-pagination-plugin.js" asp-append-version="true"></script>
    <script src="~/js/jquery.fancybox.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

InventoryProject/Views/Shared/_OrderDetails.cshtml
@model InventoryProject.Models.Order

    <div class="form-pos form-info block-width-100">
        @if ((string)@ViewData["Controller"] == "Orders")
        {
            <div class="form-info__heading">
                Working Order #@Model.Id:
            </div>
            <div class="form-info__note">
                Status:
                @if (Model.IsOpen)
                {
                    <span>Open</span>
                }
                else
                {
                    <span>Closed</span>
                }
            </div>

        }
        else
        {
            <div class="form-info__heading">
                Current Working Order:
            </div>
        }

        @if ((string)@ViewData["Controller"] == "Orders")
        {
            <div class="form-info__item">
                <div class="form-info__label">Equipment</div>
                <div class="form-info_data">
                    <a asp-controller="Equipment" asp-action="Details" asp-route-id="@Model.Equipment.Id">
                        @Model.Equipment.Title,
                        <br /> @Model.Equipment.Type,
                        <br /> @Model.Equipment.Category,
                        <br /> @Model.Equipment.Department
                    </a>
                </div>
            </div>
        }
        <div class="form-info__item">
            <div class="form-info__label">Client</div>
            <div class="form-info_data">
                <a asp-controller="Clients" asp-action="Details" asp-route-id="@Model.Contract.Client.Id">
                    @Model.Contract.Client.Name
                </a>
            </div>
        </div>
        <div class="form-info__item">
            <div class="form-info__label">Contract</div>
            <div class="form-info_data">@Model.Contract.ContractNumber</div>
        </div>
        <div class="form-info__item">
            <div class="form-info__label">Well</div>
            <div class="form-info_data">@Model.Well.Title</div>
        </div>

        @if (Model.IsOpen == true)
        {
            ViewData["EquipmentId"] = Model.Equipment.Id;
            ViewData["EntityType"] = "Order";
            ViewData["EntityId"] = Model.Id;
            ViewData["Heading"] = "Working order notes";
            <partial name="_FormAddNote" view-data="ViewData" />

            <div class="form-pos small-form">
                <div class="form-info__heading">Today's Operating Hours:</div>
                <form method="post"
                      asp-controller="Shared" asp-action="AddHours"
                      asp-route-equipmentId="@Model.Equipment.Id"
                      asp-route-orderId="@Model.Id"
                      asp-route-controllerId="@ViewData["Controller"]">
                    <div class="form-group small-fields">
                        <label class="control-label">Hours</label>
                        <input required name="hours" type="number" value="0" min="0" max="24" class="form-control" />
                    </div>
                    <div class="form-group small-fields">
                        <label class="control-label">Minutes</label>
                        <input required name="minutes" type="number" value="0" min="0" max="59" class="form-control" />
                    </div>
                    <button class="btn btn-primary">Add Hours</button>
                </form>
            </div>
        }

        <!-- Order History -->
        @{
            ViewData["Type"] = "Order";
            ViewData["EntityId"] = Model.Id;
            <partial name="_History" view-data="ViewData" />
        }

        @if (Model.IsOpen == true)
        {
            <a asp-action="CloseOrder" asp-controller="Shared" asp-route-orderId="@Model.Id" asp-route-controllerId='@ViewData["Controller"]' class="btn btn-alter btn-auto">
                Close Order
            </a>
        }

    </div>