InventoryProject/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryProject.Models
{
    public class Order
    {
        public int Id { get; set; }
        public Equipment Equipment { get; set; }
        public Contract Contract { get; set; }
        public Well Well { get; set; }
        public bool IsOpen { get; set; }
        public DateTime OrderStart { get; set; }
        public DateTime OrderFinish { get; set; }
    }
}

InventoryProject/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using InventoryProject.Helpers;
using InventoryProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace InventoryProject.Controllers
{
    public class EquipmentController : Controller
    {
        private readonly InventoryContext db;
        public EquipmentController(InventoryContext context)
        {
            db = context;
        }

        //Validation
        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyDiameter(int diameterInner, int diameterOuter)
        {
           if (diameterInner >= diameterOuter)
            {
                return Json($"Inner diameter must be smaller than outer diameter.");
            }
            return Json(true);
        }
        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyOperatingTime(int OperatingTimeMin, int OperatingTime)
        {
            if (OperatingTimeMin > OperatingTime)
            {
                return Json($"Minimal Operating Time cannot be larger than default Operating time.");
            }
            return Json(true);
        }

        // SEARCHING
        private List<Equipment> Searching(List<Equipment> equipment, string searchStatus, string searchField, string searchString)
        {
            // search field
            int result;
            bool isInt = int.TryParse(searchString, out result);
            if (string.IsNullOrEmpty(searchString)) searchString = "";
            switch (searchField)
            {
                case "Department":
                    equipment = equipment.Where(x => x.Department.ToLower()
                        .Contains(searchString.ToLower())).ToList();
                    break;
                case "Category":
                    equipment = equipment.Where(x => x.Category.ToLower()
                        .Contains(searchString.ToLower())).ToList();
                    break;
                case "Type":
                    equipment = equipment.Where(x => x.Type.ToLower()
                        .Contains(searchString.ToLower())).ToList();
                    break;
                case "Title":
                    equipment = equipment.Where(x => x.Title.ToLower()
                        .Contains(searchString.ToLower())).ToList();
                    break;
                case "SerialNumber":
                    equipment = equipment.Where(x => x.SerialNum.ToLower()
                        .Contains(searchString.ToLower())).ToList();
                    break;
                case "DiameterOuter":
                    if (isInt)
                        equipment = equipment.Where(x => x.DiameterOuter == result).ToList();
                    else
                        equipment = equipment.Where(x => x.Id == null).ToList();
                    break;
                case "DiameterInner":
                    if (isInt)
                        equipment = equipment.Where(x => x.DiameterInner == result).ToList();
                    else
                        equipment = equipment.Where(x => x.Id == null).ToList();
                    break;
                case "Length":
                    if (isInt)
                        equipment = equipment.Where(x => x.Length == result).ToList();
                    else
                        equipment = equipment.Where(x => x.Id == null).ToList();
                    break;
                default:
                    break;
            }
            // search status
            int status = -1;
            if (!string.IsNullOrEmpty(searchStatus))
            {
                if (!int.TryParse(searchStatus, out status))
                {
                    status = -1;
                }
            }
            if (status != -1)
            {
                equipment = equipment.Where(x => x.Status.Id == status).ToList();
            }

            return equipment;
        }
        // SORTING
        private List<Equipment> Sorting(string sortOrder, List<Equipment> equipment)
        {
            switch (sortOrder)
            {
                case "length_desc":
                    equipment = equipment.OrderByDescending(x => x.Length).ToList();
                    break;
                case "length":
                    equipment = equipment.OrderBy(x => x.Length).ToList();
                    break;
                case "diameterinner_desc":
                    equipment = equipment.OrderByDescending(x => x.DiameterInner).ToList();
                    break;
                case "diameterinner":
                    equipment = equipment.OrderBy(x => x.DiameterInner).ToList();
                    break;
                case "diameterouter_desc":
                    equipment = equipment.OrderByDescending(x => x.DiameterOuter).ToList();
                    break;
                case "diameterouter":
                    equipment = equipment.OrderBy(x => x.DiameterOuter).ToList();
                    break;
                case "serialnum_desc":
                    equipment = equipment.OrderByDescending(x => x.SerialNum).ToList();
                    break;
                case "serialnum":
                    equipment = equipment.OrderBy(x => x.SerialNum).ToList();
                    break;
                case "title_desc":
                    equipment = equipment.OrderByDescending(x => x.Title).ToList();
                    break;
                case "title":
                    equipment = equipment.OrderBy(x => x.Title).ToList();
                    break;
                case "type_desc":
                    equipment = equipment.OrderByDescending(x => x.Type).ToList();
                    break;
                case "type":
                    equipment = equipment.OrderBy(x => x.Type).ToList();
                    break;
                case "category_desc":
                    equipment = equipment.OrderByDescending(x => x.Category).ToList();
                    break;
                case "category":
                    equipment = equipment.OrderBy(x => x.Category).ToList();
                    break;
                case "department_desc":
                    equipment = equipment.OrderByDescending(x => x.Department).ToList();
                    break;
                case "department":
                    equipment = equipment.OrderBy(x => x.Department).ToList().ToList();
                    break;
                case "status_desc":
                    equipment = equipment.OrderByDescending(x => x.Status.Title).ToList();
                    break;
                default:
                    equipment = equipment.OrderBy(x => x.Status.Title).ToList();
                    break;
            }
            return equipment;
        }

        // Get orders
        private List<Order> GetOrders(List<Equipment> equipment)
        {
            List<Order> orders = new List<Order>();
            foreach (var item in equipment)
            {
                if (item.Status.Title == "JF")
                {
                    var tempOrders = db.Orders
                        .Include(x => x.Equipment)
                        .Include(x => x.Contract)
                        .Include(x => x.Well)
                        .ThenInclude(x => x.Client)
                        .Where(x => x.Equipment.Id == item.Id && x.IsOpen == true).ToList();
                    orders.AddRange(tempOrders);
                }
            }
            return orders;
        }

        // GET: EquipmentController
        public ActionResult Index(string oldSortOrder, string newSortOrder, string searchString, string searchField, string searchStatus, int? page)
        {
            ViewBag.CurrentFilter = searchString;
            ViewBag.SearchStatus = string.IsNullOrEmpty(searchStatus) ? "-1" : searchStatus;
            ViewBag.SearchField = string.IsNullOrEmpty(searchField) ? "Department" : searchField; 
            ViewBag.StatusList = db.EquipmentStatuses.ToList();
            var equipment = db.Equipment.Include(x => x.Status).ToList();
            ViewBag.Orders = GetOrders(equipment);

            // SEARCH
            equipment = Searching(equipment, searchStatus, searchField, searchString);

            // SORTING
            if (string.IsNullOrEmpty(newSortOrder))
            {
                newSortOrder = "status";
            }
            else if (newSortOrder == oldSortOrder)
            {
                newSortOrder += "_desc";
            }          
            ViewBag.CurrentSort = newSortOrder;
            equipment = Sorting(newSortOrder, equipment);

            if (searchString != null)
            {
                page = 1;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);


            return View(equipment.ToPagedList(pageNumber, pageSize));
        }

        // GET: EquipmentController/Details/5
        public ActionResult Details(int id)
        {
            var equipment = db.Equipment.Include("Status").FirstOrDefault(x => x.Id == id);
            switch (equipment.Status.Title)
            {
                case "RFU":
                    ViewBag.ClientList = db.Clients.OrderBy(x => x.Name).ToList();
                    ViewBag.ContractList = db.Agreements.OrderBy(x => x.Client.Id).ToList();
                    ViewBag.WellList = db.Wells.OrderBy(x => x.Client.Id).ToList();
                    break;
                case "JF":
                    var order = db.Orders.Include(x => x.Contract)
                            .ThenInclude(contract => contract.Client)
                        .Include(x => x.Well)
                        .Include(x => x.Equipment)
                        .FirstOrDefault(x => x.Equipment.Id == equipment.Id

InventoryProject/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InventoryProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace InventoryProject.Controllers
{
    public class OrdersController : Controller
    {
        private readonly InventoryContext db;
        public OrdersController(InventoryContext context)
        {
            db = context;
        }

        // SEARCH
        private List<Order> Searching(List<Order> orders, string searchStatus, string searchField, string searchString)
        {
            switch (searchField)
            {
                case "Client":
                        orders = orders.Where(x => x.Contract.Client.Name.ToLower().Contains(searchString)).ToList();
                    break;
                case "Contract":
                        orders = orders.Where(x => x.Contract.ContractNumber.ToLower().Contains(searchString)).ToList();
                    break;
                case "Well":
                        orders = orders.Where(x => x.Well.Title.ToLower().Contains(searchString)).ToList();
                    break;
                default:
                    break;
            }
            if (searchStatus == "Open")
            {
                orders = orders.Where(x => x.IsOpen == true).ToList();
            }
            else
            {
                orders = orders.Where(x => x.IsOpen == false).ToList();
            }
            return orders;
        }
        // SORT
        private List<Order> Sorting(List<Order> orders, string sortOrder)
        {
            switch (sortOrder)
            {
                case "well_desc":
                    orders = orders.OrderByDescending(x => x.Well.Title).ToList();
                    break;
                case "well":
                    orders = orders.OrderBy(x => x.Well.Title).ToList();
                    break;
                case "contract_desc":
                    orders = orders.OrderByDescending(x => x.Contract.ContractNumber).ToList();
                    break;
                case "contract":
                    orders = orders.OrderBy(x => x.Contract.ContractNumber).ToList();
                    break;
                case "client_desc":
                    orders = orders.OrderByDescending(x => x.Contract.Client.Name).ToList();
                    break;
                case "client":
                    orders = orders.OrderBy(x => x.Contract.Client.Name).ToList();
                    break;
                case "id_desc":
                    orders = orders.OrderByDescending(x => x.Id).ToList();
                    break;
                default:
                    orders = orders.OrderBy(x => x.Id).ToList();
                    break;
            }
            return orders;
        }

        // LIST
        public ActionResult Index(string oldSortOrder, string newSortOrder, string searchString, string searchField, string searchStatus, int? page)
        {
            ViewBag.CurrentFilter = searchString;

            ViewBag.SearchStatus = string.IsNullOrEmpty(searchStatus) ? "Open" : searchStatus;
            ViewBag.SearchField = string.IsNullOrEmpty(searchField) ? "Client" : searchField;
            
            var orders = db.Orders.Include(x => x.Contract)
                         .ThenInclude(contract => contract.Client)
                         .Include(x => x.Well)
                         .Include(x => x.Equipment).ToList();

            // SEARCH
            if (string.IsNullOrEmpty(searchStatus))
                searchStatus = "Open";
            if (string.IsNullOrEmpty(searchString))
                searchString = "";
            orders = Searching(orders, searchStatus, searchField, searchString);

            // SORTING
            if (string.IsNullOrEmpty(newSortOrder))
            {
                newSortOrder = "id"; 
            }
            else if (newSortOrder == oldSortOrder)
            {
                newSortOrder += "_desc";                 
            }
            orders = Sorting(orders, newSortOrder);
            ViewBag.CurrentSort = newSortOrder;

            if (searchString != null)
            {
                page = 1;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(orders.ToPagedList(pageNumber, pageSize));
        }

        // GET: OrdersController/Details/5
        public ActionResult Details(int id)
        {
            var order = db.Orders.Include(x => x.Contract)
                            .ThenInclude(contract => contract.Client)
                        .Include(x => x.Well)
                        .Include(x => x.Equipment)
                        .FirstOrDefault(x => x.Id == id);

            ViewBag.History = db.History.Include(x => x.Type)
                .Where(x => x.EntityID == id).ToList();
            return View(order);
        }


        // GET: OrdersController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: OrdersController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

InventoryProject/Views/Orders/Details.cshtml
@model InventoryProject.Models.Order

@{
    ViewData["Controller"] = "Orders";
    ViewData["History"] = ViewBag.History;
    <partial name="_OrderDetails" model="Model" view-data="ViewData" />
}

InventoryProject/Views/Orders/Index.cshtml
@model X.PagedList.IPagedList<InventoryProject.Models.Order>

@{
    ViewData["Title"] = "Orders";
}

<div class="content-heading">
    <h4>Orders</h4>
</div>

<!-- SEARCH PANEL -->
<div class="search-panel">
    @using (Html.BeginForm())
    {
        <div class="search-field">
            <div class="search-label">
                <label class="control-label">Status:</label>
            </div>
            <div class="search-select">
                <select name="searchStatus" class="form-select">
                    <option selected value="Open">Open</option>
                    <option value="Closed">Closed</option>
                </select>
            </div>
        </div>
        <div class="search-field">
            <div class="search-label">
                <label class="control-label">Field:</label>
            </div>
            <div class="search-select">
                <select name="searchField" class="form-select">
                    <option selected value="Client">Client</option>
                    <option value="Contract">Contract</option>
                    <option value="Well">Well</option>
                </select>
            </div>
        </div>
        <div class="search-field search-field-input">
            <div class="search-label">
                <label class="control-label">Search:</label>
            </div>
            <div class="search-textbox">
                @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
            </div>
        </div>
        <button class="btn btn-primary search-btn">Search</button>
        <a asp-action="Index" class="btn btn-alter btn-refresh">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22"><path d="m120.6 38.723c-3.312-7.713-7.766-14.367-13.36-19.961-5.595-5.594-12.248-10.05-19.962-13.361-7.713-3.314-15.805-4.97-24.278-4.97-7.984 0-15.71 1.506-23.18 4.521-7.468 3.01-14.11 7.265-19.92 12.751l-10.593-10.511c-1.63-1.684-3.503-2.064-5.622-1.141-2.173.924-3.259 2.527-3.259 4.808v36.5c0 1.412.516 2.634 1.548 3.666 1.033 1.032 2.255 1.548 3.667 1.548h36.5c2.282 0 3.884-1.086 4.807-3.259.923-2.118.543-3.992-1.141-5.622l-11.162-11.243c3.803-3.585 8.148-6.341 13.04-8.27 4.889-1.928 9.994-2.893 15.317-2.893 5.649 0 11.04 1.101 16.17 3.3 5.133 2.2 9.572 5.174 13.32 8.922 3.748 3.747 6.722 8.187 8.922 13.32 2.199 5.133 3.299 10.523 3.299 16.17 0 5.65-1.1 11.04-3.299 16.17-2.2 5.133-5.174 9.573-8.922 13.321-3.748 3.748-8.188 6.722-13.32 8.921-5.133 2.2-10.525 3.3-16.17 3.3-6.464 0-12.574-1.412-18.332-4.236-5.757-2.824-10.618-6.816-14.583-11.977-.38-.543-1-.87-1.874-.979-.815 0-1.494.244-2.037.733l-11.162 11.244c-.434.436-.665.991-.692 1.67-.027.68.15 1.29.53 1.833 5.921 7.17 13.09 12.724 21.509 16.661 8.419 3.937 17.3 5.907 26.642 5.907 8.473 0 16.566-1.657 24.279-4.97 7.713-3.313 14.365-7.768 19.961-13.361 5.594-5.596 10.05-12.248 13.361-19.961 3.313-7.713 4.969-15.807 4.969-24.279 0-8.474-1.657-16.564-4.97-24.277" transform="matrix(.12785 0 0 .12786 2.95 2.948)" fill="#ffffff" /></svg>
        </a>
    }
</div>

<table class="table">
    <thead>
        <tr>
            <th class="@(ViewBag.CurrentSort.ToString() == "id" ? "sort-asc" : @ViewBag.CurrentSort.ToString() == "id_desc" ? "sort-desc" : " ")">
                @Html.ActionLink("Id", "Index", new { oldSortOrder = ViewBag.CurrentSort, newSortOrder = "id", searchString = ViewBag.CurrentFilter, searchStatus = ViewBag.SearchStatus })
            </th>
            <th class="@(ViewBag.CurrentSort.ToString() == "client" ? "sort-asc" : @ViewBag.CurrentSort.ToString() == "client_desc" ? "sort-desc" : " ")">
                @Html.ActionLink("Client", "Index", new { oldSortOrder = ViewBag.CurrentSort, newSortOrder = "client", searchString = ViewBag.CurrentFilter, searchStatus = ViewBag.SearchStatus })
            </th>
            <th class="@(ViewBag.CurrentSort.ToString() == "contract" ? "sort-asc" : @ViewBag.CurrentSort.ToString() == "contract_desc" ? "sort-desc" : " ")">
                @Html.ActionLink("Contract", "Index", new { oldSortOrder = ViewBag.CurrentSort, newSortOrder = "contract", searchString = ViewBag.CurrentFilter, searchStatus = ViewBag.SearchStatus })
            </th>
            <th class="@(ViewBag.CurrentSort.ToString() == "well" ? "sort-asc" : @ViewBag.CurrentSort.ToString() == "well_desc" ? "sort-desc" : " ")">
                @Html.ActionLink("Well", "Index", new { oldSortOrder = ViewBag.CurrentSort, newSortOrder = "well", searchString = ViewBag.CurrentFilter, searchStatus = ViewBag.SearchStatus })
            </th>
            <th>
                Equipment
            </th>
            <th>
                <!-- actions -->
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    <!-- client -->
                    @Html.DisplayFor(modelItem => item.Contract.Client.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contract.ContractNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Well.Title)
                </td>
                <td>
                    <a asp-controller="Equipment" asp-action="Details" asp-route-id="@item.Equipment.Id">
                        @Html.DisplayFor(modelItem => item.Equipment.Title), <br />
                        @Html.DisplayFor(modelItem => item.Equipment.Category), <br />
                        @Html.DisplayFor(modelItem => item.Equipment.Department)
                    </a>
                </td>
                <td>
                    <a class="btn" asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    var status = '@ViewBag.SearchStatus';
    $("select[name='searchStatus']").find('option[value="' + status + '"]').prop("selected", true);

    var category = '@ViewBag.SearchField';
    $("select[name='searchField']").find('option[value="' + category + '"]').prop("selected", true);

</script> 